#define SFX_ANKH	0
#define SFX_ARROW	1
#define SFX_ARROW_HIT	2
#define SFX_BOW	3
#define SFX_BULLET	4
#define SFX_CHANGE	5
#define SFX_CHECKPOINT	6
#define SFX_CLIMB	7
#define SFX_COIN	8
#define SFX_DOOR	9
#define SFX_ENEMY_DIE	10
#define SFX_EXIT	11
#define SFX_JUMP	12
#define SFX_KEY	13
#define SFX_PLAYER_DIE	14
#define SFX_TELEPORT	15
#define SFX_TITLE	16
#define SFX_URN_BREAK	17
#define SFX_WALK	18
#define MSL_NSONGS	0
#define MSL_NSAMPS	19
#define MSL_BANKSIZE	19
